In [ ]:

#Import libraries
import pandas as pd
import re

In [2]:
#Load dataset
df = pd.read_csv("../data/raw/final_dataset.csv", encoding="utf-8-sig")
df.head()

                                             Comment     Label
0                  movie vara level la Erika poguthu  NON_HATE
1          Padam nalla comedy padama irukum polaye..  NON_HATE
2  karthick subburaj anne .... intha padam vetri ...  NON_HATE
3  கவுண்டர் தேவர்.சார்பாக வெற்றி பெற வாழ்த்துக்கள் 🦁  NON_HATE
4  ippo intha trailer ah parkuravana oru like pod...  NON_HATE

In [3]:
#Remove unwanted unnamed columns
df = df.loc[:, ~df.columns.str.contains("^Unnamed:")]

In [4]:
#Remove empty comments
df = df.dropna(subset=["Comment"])

In [5]:
#Strip whitespace
df["Comment"] = df["Comment"].astype(str).str.strip()

In [6]:
#Normalize label text
df["Label"] = df["Label"].str.upper()

In [7]:
#Remove URLs
df["Comment"] = df["Comment"].apply(
    lambda x: re.sub(r"http\S+|www\S+", "", x)
)

In [8]:
#Remove user mentions (@name)
df["Comment"] = df["Comment"].apply(
    lambda x: re.sub(r"@\w+", "", x)
)

In [9]:
#Normalize repeated characters
df["Comment"] = df["Comment"].apply(
    lambda x: re.sub(r"(.)\1{2,}", r"\1\1", x)
)

In [10]:
#Lowercasing (for ML baselines)
df["Comment_clean"] = df["Comment"].str.lower()

In [11]:
#Encode labels for ML
Label_map = {"NON_HATE": 0, "HATE": 1}
df["Label_id"] = df["Label"].map(Label_map)

In [12]:
#Save processed data
df.to_csv(
    "../data/processed/processed_dataset.csv",
    index=False,
    encoding="utf-8-sig"
)

df.head()

,Comment,Label,Comment_clean,Label_id
0,movie vara level la Erika poguthu,NON_HATE,movie vara level la erika poguthu,0
1,Padam nalla comedy padama irukum polaye..,NON_HATE,padam nalla comedy padama irukum polaye..,0
2,karthick subburaj anne .. intha padam vetri ad...,NON_HATE,karthick subburaj anne .. intha padam vetri ad...,0
3,கவுண்டர் தேவர்.சார்பாக வெற்றி பெற வாழ்த்துக்கள் 🦁,NON_HATE,கவுண்டர் தேவர்.சார்பாக வெற்றி பெற வாழ்த்துக்கள் 🦁,0
4,ippo intha trailer ah parkuravana oru like pod...,NON_HATE,ippo intha trailer ah parkuravana oru like pod...,0